#!/usr/bin/env bash
set -euo pipefail

TEXTTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$TEXTTS_DIR/.." && pwd)"

DOMAINS="${DOMAINS:-}"
DOMAIN="${1:-${DOMAIN:-}}"
if [[ -z "$DOMAINS" && -z "$DOMAIN" ]]; then
  DOMAIN="Energy"
fi

TIMEMMD_ROOT="${TIMEMMD_ROOT:-$PROJECT_ROOT/Time-MMD}"
TARGET_COL="${TARGET_COL:-OT}"
LOOKBACK="${LOOKBACK:-32}"
HORIZON="${HORIZON:-8}"
STRIDE="${STRIDE:-16}"
MAX_WINDOWS="${MAX_WINDOWS:-4}"
BATCH_SIZE="${BATCH_SIZE:-1}"
MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-0.6B-Base}"
TORCH_DTYPE="${TORCH_DTYPE:-}"
DEVICE_MAP="${DEVICE_MAP:-}"
DEVICE="${DEVICE:-cpu}"
LOCAL_FILES_ONLY="${LOCAL_FILES_ONLY:-0}"

USE_FIXED_SPLITS="${USE_FIXED_SPLITS:-1}"
TRAIN_SPLIT="${TRAIN_SPLIT:-train}"
PRETRAIN_EVAL_SPLIT="${PRETRAIN_EVAL_SPLIT:-val}"
SFT_EVAL_SPLIT="${SFT_EVAL_SPLIT:-val}"
FINAL_EVAL_SPLIT="${FINAL_EVAL_SPLIT:-test}"
SPLIT_VAL_RATIO="${SPLIT_VAL_RATIO:-0.1}"
SPLIT_TEST_RATIO="${SPLIT_TEST_RATIO:-0.1}"

PRETRAIN_STEPS="${PRETRAIN_STEPS:-1}"
PRETRAIN_LEARNING_RATE="${PRETRAIN_LEARNING_RATE:-1e-4}"
PRETRAIN_PRED_PROBABILITY="${PRETRAIN_PRED_PROBABILITY:-0.7}"
PRETRAIN_EVAL_RATIO="${PRETRAIN_EVAL_RATIO:-0.0}"
PRETRAIN_EVAL_MAX_SAMPLES="${PRETRAIN_EVAL_MAX_SAMPLES:-2}"

POST_PRETRAIN_MAX_SAMPLES="${POST_PRETRAIN_MAX_SAMPLES:-2}"
POST_PRETRAIN_POINT_STRATEGY="${POST_PRETRAIN_POINT_STRATEGY:-greedy}"
POST_PRETRAIN_POINT_TEMPERATURE="${POST_PRETRAIN_POINT_TEMPERATURE:-1.0}"
POST_PRETRAIN_POINT_TOP_P="${POST_PRETRAIN_POINT_TOP_P:-1.0}"
POST_PRETRAIN_NUM_PROB_SAMPLES="${POST_PRETRAIN_NUM_PROB_SAMPLES:-4}"
POST_PRETRAIN_PROB_TEMPERATURE="${POST_PRETRAIN_PROB_TEMPERATURE:-1.0}"
POST_PRETRAIN_PROB_TOP_P="${POST_PRETRAIN_PROB_TOP_P:-0.9}"

SFT_STEPS="${SFT_STEPS:-1}"
SFT_LEARNING_RATE="${SFT_LEARNING_RATE:-1e-4}"
SFT_USE_LORA="${SFT_USE_LORA:-0}"
SFT_EVAL_RATIO="${SFT_EVAL_RATIO:-0.0}"
SFT_EVAL_MAX_SAMPLES="${SFT_EVAL_MAX_SAMPLES:-2}"

POST_SFT_MAX_SAMPLES="${POST_SFT_MAX_SAMPLES:-2}"
POST_SFT_POINT_STRATEGY="${POST_SFT_POINT_STRATEGY:-greedy}"
POST_SFT_POINT_TEMPERATURE="${POST_SFT_POINT_TEMPERATURE:-1.0}"
POST_SFT_POINT_TOP_P="${POST_SFT_POINT_TOP_P:-1.0}"
POST_SFT_NUM_PROB_SAMPLES="${POST_SFT_NUM_PROB_SAMPLES:-4}"
POST_SFT_PROB_TEMPERATURE="${POST_SFT_PROB_TEMPERATURE:-1.0}"
POST_SFT_PROB_TOP_P="${POST_SFT_PROB_TOP_P:-0.9}"

BASE_RUN_LABEL="${BASE_RUN_LABEL:-${DOMAIN:-joint}}"
PRETRAIN_RUN_LABEL="${PRETRAIN_RUN_LABEL:-${BASE_RUN_LABEL}_pretrain}"
POST_PRETRAIN_EVAL_RUN_LABEL="${POST_PRETRAIN_EVAL_RUN_LABEL:-${BASE_RUN_LABEL}_post_pretrain_eval}"
SFT_RUN_LABEL="${SFT_RUN_LABEL:-${BASE_RUN_LABEL}_sft}"
POST_SFT_EVAL_RUN_LABEL="${POST_SFT_EVAL_RUN_LABEL:-${BASE_RUN_LABEL}_post_sft_eval}"

PRETRAIN_OUTPUT_DIR="${PRETRAIN_OUTPUT_DIR:-$PROJECT_ROOT/outputs/timemmd_pretrain_${PRETRAIN_RUN_LABEL}}"
POST_PRETRAIN_EVAL_OUTPUT_DIR="${POST_PRETRAIN_EVAL_OUTPUT_DIR:-$PROJECT_ROOT/outputs/timemmd_eval_${POST_PRETRAIN_EVAL_RUN_LABEL}}"
SFT_OUTPUT_DIR="${SFT_OUTPUT_DIR:-$PROJECT_ROOT/outputs/timemmd_sft_${SFT_RUN_LABEL}}"
POST_SFT_EVAL_OUTPUT_DIR="${POST_SFT_EVAL_OUTPUT_DIR:-$PROJECT_ROOT/outputs/timemmd_eval_${POST_SFT_EVAL_RUN_LABEL}}"

export PYTHONPATH="$PROJECT_ROOT${PYTHONPATH:+:$PYTHONPATH}"
cd "$PROJECT_ROOT"

run_with_domain_env() {
  local script_path="$1"
  shift

  if [[ -n "$DOMAINS" ]]; then
    DOMAINS="$DOMAINS" "$script_path" "$@"
  else
    DOMAIN="$DOMAIN" "$script_path" "$DOMAIN" "$@"
  fi
}

printf 'Running full Time-MMD pipeline with target=%s lookback=%s horizon=%s device=%s\n' "$TARGET_COL" "$LOOKBACK" "$HORIZON" "$DEVICE"
printf 'Stage 1/4: pretrain -> %s\n' "$PRETRAIN_OUTPUT_DIR"

TIMEMMD_ROOT="$TIMEMMD_ROOT" \
TARGET_COL="$TARGET_COL" \
LOOKBACK="$LOOKBACK" \
HORIZON="$HORIZON" \
STRIDE="$STRIDE" \
MAX_WINDOWS="$MAX_WINDOWS" \
BATCH_SIZE="$BATCH_SIZE" \
STEPS="$PRETRAIN_STEPS" \
LEARNING_RATE="$PRETRAIN_LEARNING_RATE" \
PRED_PROBABILITY="$PRETRAIN_PRED_PROBABILITY" \
MODEL_NAME="$MODEL_NAME" \
TORCH_DTYPE="$TORCH_DTYPE" \
DEVICE_MAP="$DEVICE_MAP" \
DEVICE="$DEVICE" \
LOCAL_FILES_ONLY="$LOCAL_FILES_ONLY" \
USE_FIXED_SPLITS="$USE_FIXED_SPLITS" \
TRAIN_SPLIT="$TRAIN_SPLIT" \
EVAL_SPLIT="$PRETRAIN_EVAL_SPLIT" \
SPLIT_VAL_RATIO="$SPLIT_VAL_RATIO" \
SPLIT_TEST_RATIO="$SPLIT_TEST_RATIO" \
EVAL_RATIO="$PRETRAIN_EVAL_RATIO" \
EVAL_MAX_SAMPLES="$PRETRAIN_EVAL_MAX_SAMPLES" \
RUN_LABEL="$PRETRAIN_RUN_LABEL" \
OUTPUT_DIR="$PRETRAIN_OUTPUT_DIR" \
run_with_domain_env "$TEXTTS_DIR/scripts/run_timemmd_pretrain.sh"

printf 'Stage 2/4: post-pretrain eval -> %s\n' "$POST_PRETRAIN_EVAL_OUTPUT_DIR"

TIMEMMD_ROOT="$TIMEMMD_ROOT" \
TARGET_COL="$TARGET_COL" \
LOOKBACK="$LOOKBACK" \
HORIZON="$HORIZON" \
STRIDE="$STRIDE" \
MAX_WINDOWS="$MAX_WINDOWS" \
SPLIT="$FINAL_EVAL_SPLIT" \
SPLIT_VAL_RATIO="$SPLIT_VAL_RATIO" \
SPLIT_TEST_RATIO="$SPLIT_TEST_RATIO" \
MAX_SAMPLES="$POST_PRETRAIN_MAX_SAMPLES" \
MODEL_NAME="$MODEL_NAME" \
CHECKPOINT_DIR="$PRETRAIN_OUTPUT_DIR" \
TORCH_DTYPE="$TORCH_DTYPE" \
DEVICE_MAP="$DEVICE_MAP" \
DEVICE="$DEVICE" \
LOCAL_FILES_ONLY="$LOCAL_FILES_ONLY" \
POINT_STRATEGY="$POST_PRETRAIN_POINT_STRATEGY" \
POINT_TEMPERATURE="$POST_PRETRAIN_POINT_TEMPERATURE" \
POINT_TOP_P="$POST_PRETRAIN_POINT_TOP_P" \
NUM_PROB_SAMPLES="$POST_PRETRAIN_NUM_PROB_SAMPLES" \
PROB_TEMPERATURE="$POST_PRETRAIN_PROB_TEMPERATURE" \
PROB_TOP_P="$POST_PRETRAIN_PROB_TOP_P" \
RUN_LABEL="$POST_PRETRAIN_EVAL_RUN_LABEL" \
OUTPUT_DIR="$POST_PRETRAIN_EVAL_OUTPUT_DIR" \
run_with_domain_env "$TEXTTS_DIR/scripts/run_timemmd_eval.sh"

printf 'Stage 3/4: sft -> %s\n' "$SFT_OUTPUT_DIR"

TIMEMMD_ROOT="$TIMEMMD_ROOT" \
TARGET_COL="$TARGET_COL" \
LOOKBACK="$LOOKBACK" \
HORIZON="$HORIZON" \
STRIDE="$STRIDE" \
MAX_WINDOWS="$MAX_WINDOWS" \
BATCH_SIZE="$BATCH_SIZE" \
STEPS="$SFT_STEPS" \
LEARNING_RATE="$SFT_LEARNING_RATE" \
MODEL_NAME="$MODEL_NAME" \
CHECKPOINT_DIR="$PRETRAIN_OUTPUT_DIR" \
TORCH_DTYPE="$TORCH_DTYPE" \
DEVICE_MAP="$DEVICE_MAP" \
DEVICE="$DEVICE" \
LOCAL_FILES_ONLY="$LOCAL_FILES_ONLY" \
USE_LORA="$SFT_USE_LORA" \
USE_FIXED_SPLITS="$USE_FIXED_SPLITS" \
TRAIN_SPLIT="$TRAIN_SPLIT" \
EVAL_SPLIT="$SFT_EVAL_SPLIT" \
SPLIT_VAL_RATIO="$SPLIT_VAL_RATIO" \
SPLIT_TEST_RATIO="$SPLIT_TEST_RATIO" \
EVAL_RATIO="$SFT_EVAL_RATIO" \
EVAL_MAX_SAMPLES="$SFT_EVAL_MAX_SAMPLES" \
RUN_LABEL="$SFT_RUN_LABEL" \
OUTPUT_DIR="$SFT_OUTPUT_DIR" \
run_with_domain_env "$TEXTTS_DIR/scripts/run_timemmd_sft.sh"

printf 'Stage 4/4: post-sft eval -> %s\n' "$POST_SFT_EVAL_OUTPUT_DIR"

TIMEMMD_ROOT="$TIMEMMD_ROOT" \
TARGET_COL="$TARGET_COL" \
LOOKBACK="$LOOKBACK" \
HORIZON="$HORIZON" \
STRIDE="$STRIDE" \
MAX_WINDOWS="$MAX_WINDOWS" \
SPLIT="$FINAL_EVAL_SPLIT" \
SPLIT_VAL_RATIO="$SPLIT_VAL_RATIO" \
SPLIT_TEST_RATIO="$SPLIT_TEST_RATIO" \
MAX_SAMPLES="$POST_SFT_MAX_SAMPLES" \
MODEL_NAME="$MODEL_NAME" \
CHECKPOINT_DIR="$SFT_OUTPUT_DIR" \
TORCH_DTYPE="$TORCH_DTYPE" \
DEVICE_MAP="$DEVICE_MAP" \
DEVICE="$DEVICE" \
LOCAL_FILES_ONLY="$LOCAL_FILES_ONLY" \
POINT_STRATEGY="$POST_SFT_POINT_STRATEGY" \
POINT_TEMPERATURE="$POST_SFT_POINT_TEMPERATURE" \
POINT_TOP_P="$POST_SFT_POINT_TOP_P" \
NUM_PROB_SAMPLES="$POST_SFT_NUM_PROB_SAMPLES" \
PROB_TEMPERATURE="$POST_SFT_PROB_TEMPERATURE" \
PROB_TOP_P="$POST_SFT_PROB_TOP_P" \
RUN_LABEL="$POST_SFT_EVAL_RUN_LABEL" \
OUTPUT_DIR="$POST_SFT_EVAL_OUTPUT_DIR" \
run_with_domain_env "$TEXTTS_DIR/scripts/run_timemmd_eval.sh"

printf '\nFull pipeline finished.\n'
printf '  pretrain checkpoint: %s\n' "$PRETRAIN_OUTPUT_DIR"
printf '  post-pretrain eval:  %s\n' "$POST_PRETRAIN_EVAL_OUTPUT_DIR"
printf '  sft checkpoint:      %s\n' "$SFT_OUTPUT_DIR"
printf '  post-sft eval:       %s\n' "$POST_SFT_EVAL_OUTPUT_DIR"
