#!/usr/bin/env bash
set -euo pipefail

TEXTTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$TEXTTS_DIR/.." && pwd)"

DOMAIN="${1:-${DOMAIN:-Energy}}"
if [[ -n "${DOMAINS:-}" ]]; then
  echo "This script is single-domain only. Use DOMAIN or the first positional argument, not DOMAINS." >&2
  exit 1
fi

TIMEMMD_ROOT="${TIMEMMD_ROOT:-$PROJECT_ROOT/Time-MMD}"
TARGET_COL="${TARGET_COL:-OT}"
LOOKBACK="${LOOKBACK:-32}"
HORIZON="${HORIZON:-8}"
STRIDE="${STRIDE:-16}"
MAX_WINDOWS="${MAX_WINDOWS:-4}"
BATCH_SIZE="${BATCH_SIZE:-1}"
MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-0.6B-Base}"
TORCH_DTYPE="${TORCH_DTYPE:-}"
DEVICE_MAP="${DEVICE_MAP:-}"
DEVICE="${DEVICE:-cpu}"
LOCAL_FILES_ONLY="${LOCAL_FILES_ONLY:-0}"

PRETRAIN_STEPS="${PRETRAIN_STEPS:-1}"
PRETRAIN_LEARNING_RATE="${PRETRAIN_LEARNING_RATE:-1e-4}"
PRETRAIN_PRED_PROBABILITY="${PRETRAIN_PRED_PROBABILITY:-0.7}"
PRETRAIN_EVAL_RATIO="${PRETRAIN_EVAL_RATIO:-0.0}"
PRETRAIN_EVAL_MAX_SAMPLES="${PRETRAIN_EVAL_MAX_SAMPLES:-2}"
PRETRAIN_RUN_LABEL="${PRETRAIN_RUN_LABEL:-${DOMAIN}_pretrain}"
PRETRAIN_OUTPUT_DIR="${PRETRAIN_OUTPUT_DIR:-$PROJECT_ROOT/outputs/timemmd_pretrain_${PRETRAIN_RUN_LABEL}}"

SFT_STEPS="${SFT_STEPS:-1}"
SFT_LEARNING_RATE="${SFT_LEARNING_RATE:-1e-4}"
SFT_USE_LORA="${SFT_USE_LORA:-0}"
SFT_EVAL_RATIO="${SFT_EVAL_RATIO:-0.0}"
SFT_EVAL_MAX_SAMPLES="${SFT_EVAL_MAX_SAMPLES:-2}"
SFT_RUN_LABEL="${SFT_RUN_LABEL:-${DOMAIN}_sft_from_pretrain}"
SFT_OUTPUT_DIR="${SFT_OUTPUT_DIR:-$PROJECT_ROOT/outputs/timemmd_sft_${SFT_RUN_LABEL}}"

cd "$PROJECT_ROOT"
export PYTHONPATH="$PROJECT_ROOT${PYTHONPATH:+:$PYTHONPATH}"

printf 'Running single-domain pipeline for domain=%s\n' "$DOMAIN"
printf 'Stage 1/2: pretrain -> %s\n' "$PRETRAIN_OUTPUT_DIR"

DOMAIN="$DOMAIN" \
TIMEMMD_ROOT="$TIMEMMD_ROOT" \
TARGET_COL="$TARGET_COL" \
LOOKBACK="$LOOKBACK" \
HORIZON="$HORIZON" \
STRIDE="$STRIDE" \
MAX_WINDOWS="$MAX_WINDOWS" \
BATCH_SIZE="$BATCH_SIZE" \
STEPS="$PRETRAIN_STEPS" \
LEARNING_RATE="$PRETRAIN_LEARNING_RATE" \
PRED_PROBABILITY="$PRETRAIN_PRED_PROBABILITY" \
MODEL_NAME="$MODEL_NAME" \
TORCH_DTYPE="$TORCH_DTYPE" \
DEVICE_MAP="$DEVICE_MAP" \
DEVICE="$DEVICE" \
LOCAL_FILES_ONLY="$LOCAL_FILES_ONLY" \
EVAL_RATIO="$PRETRAIN_EVAL_RATIO" \
EVAL_MAX_SAMPLES="$PRETRAIN_EVAL_MAX_SAMPLES" \
RUN_LABEL="$PRETRAIN_RUN_LABEL" \
OUTPUT_DIR="$PRETRAIN_OUTPUT_DIR" \
bash "$TEXTTS_DIR/scripts/run_timemmd_pretrain.sh" "$DOMAIN"

printf 'Stage 2/2: sft -> %s\n' "$SFT_OUTPUT_DIR"

DOMAIN="$DOMAIN" \
TIMEMMD_ROOT="$TIMEMMD_ROOT" \
TARGET_COL="$TARGET_COL" \
LOOKBACK="$LOOKBACK" \
HORIZON="$HORIZON" \
STRIDE="$STRIDE" \
MAX_WINDOWS="$MAX_WINDOWS" \
BATCH_SIZE="$BATCH_SIZE" \
STEPS="$SFT_STEPS" \
LEARNING_RATE="$SFT_LEARNING_RATE" \
MODEL_NAME="$MODEL_NAME" \
TORCH_DTYPE="$TORCH_DTYPE" \
DEVICE_MAP="$DEVICE_MAP" \
DEVICE="$DEVICE" \
LOCAL_FILES_ONLY="$LOCAL_FILES_ONLY" \
USE_LORA="$SFT_USE_LORA" \
EVAL_RATIO="$SFT_EVAL_RATIO" \
EVAL_MAX_SAMPLES="$SFT_EVAL_MAX_SAMPLES" \
RUN_LABEL="$SFT_RUN_LABEL" \
OUTPUT_DIR="$SFT_OUTPUT_DIR" \
CHECKPOINT_DIR="$PRETRAIN_OUTPUT_DIR" \
bash "$TEXTTS_DIR/scripts/run_timemmd_sft.sh" "$DOMAIN"

printf 'Single-domain pipeline finished. pretrain=%s sft=%s\n' "$PRETRAIN_OUTPUT_DIR" "$SFT_OUTPUT_DIR"
